### ISSUE TITLE
Unable to logout

### ISSUE THREAD

**Issue by Beny406** [pac4j/spark-pac4j-demo#4]
I am unable to logout. I start the application as instructed. Login using basicAuth and than I am unable to logout. The only think which helpes is to restart browser. Reproduced in IE, FF, Chrome.

**Comment by leleuj** [comment]
Does the logout work using Facebook? Are you sure your basic auth credentials are not saved by the browser?

**Comment by Beny406** [comment]
No, it doesnt. I have tried to delete session cookie from browser, but it reappears after refresh.

**Comment by leleuj** [comment]
I understand. The basic auth is saved by your browser, which automatically and transparently re-authenticates you. But you have a similar problem with Facebook: when you logout in the application, it's a local logout (the session cookie is destroyed), though you are still authenticated at the Facebook level (you can confirm that by calling: www.facebook.com -> you are authenticated).

Aside from the basic auth issue, you have two kinds of logout: local and central. Currently, pac4j does not handle centralized logout, only local logout, which means you will be logged out from your webapp but automatically and transparently re-authenticated when accessing a protected url as you are still authenticated by the central identity server. You can handle that by calling: https://www.facebook.com/logout.php to perform a central logout.

**Comment by mbenmass** [comment]
I have tried what you suggested above and I am indeed logged out only after I disconnect from FB.
Do I have to implement a LogoutLogic in order to redirect the user to https://www.facebook.com/logout.php then back to my main page ?
How can I use pac4j-spark to perform that ?
Thank you

**Comment by millross** [comment]
With respect, your users aren't going to expect your application to log them out of Facebook. The whole point of Facebook-based auth is that your users can log into facebook once and log into many applications without logging in again. IMO, if you're using a public auth mechanism like Facebook, Google, Twitter, you should not perform a central logout on their behalf. If you want to force someone to re-enter credentials, don't use public services to do so.

Right now, what happens is: user logs into Facebook, reads facebook posts (for example), maybe connects to Strava, then authenticates with your app using facebook. Uses your app a bit, then logs out of your app. Then they go back to their facebook page and they've been logged out because your app did so. That's not what they will expect to happen.

**Comment by mbenmass** [comment]
Thank you for your answer. I am new to public services and I figured this out in the meanwhile.
Now, my users are able to connect to my app using their Facebook credentials.

The only issue I am facing is that I set the Fields and the Scope of my FacebookClient, but the user is still able to decide that he is not willing to share his "email" for example. So I created an authorizer that checks that the access to all requested fields have been authorized by the user.

`public class FacebookAuthorizer extends ProfileAuthorizer<FacebookProfile> {

	@Override
	public boolean isAuthorized(WebContext context, List<FacebookProfile> profiles) throws HttpAction {
		return isAllAuthorized(context, profiles);
	}

	@Override
	protected boolean isProfileAuthorized(WebContext context, FacebookProfile profile) throws HttpAction {
		for (String field : SecurityConfigFactory.FACEBOOK_FIELDS) {
			if (profile.getAttribute(field) == null) {
				SparkWebContext sparkContext = (SparkWebContext) context;
				return false;
			}
		}
		return true;
	}
}`

It works fine and if the user is redirected to my 403 page if he unchecks one of the requested fields.
Unfortunately, if I refresh the web page, I am able to access to the protected page.
Can you please help me solving this issue ?

The below line allow me to redirect my user to the logout page 👍 sparkContext.getSparkResponse().redirect(Application.LOGOUT_URL);`

Thanks a lot
Mehdi

**Comment by leleuj** [comment]
This is very strange: it should work as authorizations are checked every time you access a protected URL.
Can you put a breakpoint in your `Authorizer` to check if it is really called the second time or can you put the `org.pac4j` package at the DEBUG level and post the logs?

**Comment by mbenmass** [comment]
Hi,
First thank you very much for your help.

Actually, I found out what was happening and it is related to the fact that when a user logs in and decides not to share his email address for example, FB grants a "limited" access to my application.
On subsequent refreshes, I only get a 403 error.
Ideally, I would like the app to redirect to the BASE URL, user being logged out.
If he decides to LOG IN again, then the app will request Facebook again for the access to the email address. Is that even possible ? Otherwise are there other alternatives please ?

Thanks again.

**Comment by mbenmass** [comment]
To be clearer, my Authorizer looks like this now :
`public class FacebookAuthorizer extends ProfileAuthorizer<FacebookProfile> {

	@Override
	public boolean isAuthorized(WebContext context, List<FacebookProfile> profiles) throws HttpAction {
		return isAllAuthorized(context, profiles);
	}

	@Override
	protected boolean isProfileAuthorized(WebContext context, FacebookProfile profile) throws HttpAction {
		for (String field : SecurityConfigFactory.FACEBOOK_FIELDS) {
			if (profile.getAttribute(field) == null) {
				SparkWebContext sparkContext = (SparkWebContext) context;
				sparkContext.getSparkResponse().redirect(Application.APPLICATION_BASE_URL);
				return false;
			}
		}
		return true;
	}

}`

But if I go to the login page, I systematically get redirected to the Base URL, as if the profile is created and saved in the session without an email, so the authorizer keeps sending the user to the base URL.

Can i redirect again to FB to ask for the email ?

**Comment by leleuj** [comment]
So you can locally log out:

```java
ProfileManager manager = new ProfileManager(context);
manager.logout();
```

Then, you can force to redirect to some URL:

```java
throw new HttpAction.redirect("force a redirection", context, redirectUrl);
```

**Comment by mbenmass** [comment]
I tried what you suggested above : 
`
	@Override
	protected boolean isProfileAuthorized(WebContext context, FacebookProfile profile) throws HttpAction {
		for (String field : SecurityConfigFactory.FACEBOOK_FIELDS) {
			if (profile.getAttribute(field) == null) {
				ProfileManager<FacebookProfile> manager = new ProfileManager<FacebookProfile>(context);
				manager.logout();
				throw HttpAction.redirect(field + " MISSING", context, Application.APPLICATION_BASE_URL);
			}
		}
		//check scopes
		return true;
	}
`
and I still have the same issue.
I remove the application access to Facebook.

I go to the Base URL, I click on the Login link, I am prompted to accept the accessto Facebook, I uncheck "Email address", I validate, then I get redirected to the Base URL.
Clicking now on the Login link keeps redirecting me to the Base URL.

It seems that even if I logout from the Profile Manager, somehow when I try to login again, since my FB is still connected, it automatically retrieves the session.

**Comment by leleuj** [comment]
OK. I guess we need to trigger a Facebook central logout in that case to make FB forget the previous authentication (the one without the email). Or you can display some error page where you describe the issue: "You cannot access this app as you didn't not granted the email property. Please log out from FB and log in again".

**Comment by millross** [comment]
Once the app has been given its privileges for a given facebook user, I'm not convinced logging out of facebook will change that. Surely the app's privileges for the user on facebook survive longer than the facebook login.

**Comment by mbenmass** [comment]
It indeed doesn't change it. I just tried the following steps :
- go to login page
- uncheck "email"
- accept facebook access
---> redirected to Base URL
- I am not authentified and clicking on login again just gets me redirected again to the Base URL
- I am not able to identify myself anymore

**Comment by leleuj** [comment]
Yes indeed, you certainly need to revoke the access granted by FB to the app. I guess that the best here is to display a proper error page.

**Comment by millross** [comment]
+1. I think this requires a page which says “you need the following permissions granted to your application - please log into facebook and grant them or remove access so you can reconnect” or words to that effect.

**Comment by mbenmass** [comment]
Understood and agreed upon.
Thank you both for your help.
